export const AGRICULTURAL_CONDITIONS = {
  NORMAL: "NORMAL",
  MOISTURE_STRESS: "MOISTURE_STRESS",
  DROUGHT_RISK: "DROUGHT_RISK",
  EXCESSIVE_MOISTURE: "EXCESSIVE_MOISTURE",
  WATERLOGGING_RISK: "WATERLOGGING_RISK",
  FLOOD_RISK: "FLOOD_RISK",
  PH_LOW: "PH_LOW",
  PH_HIGH: "PH_HIGH",
  NUTRIENT_DEFICIENCY_RISK: "NUTRIENT_DEFICIENCY_RISK",
  TEMPERATURE_STRESS: "TEMPERATURE_STRESS",
  HUMIDITY_STRESS: "HUMIDITY_STRESS",
  LIGHT_STRESS: "LIGHT_STRESS",
  PEST_RISK: "PEST_RISK",
  DISEASE_RISK: "DISEASE_RISK",
  MULTIPLE_STRESS: "MULTIPLE_STRESS",
  SENSOR_ERROR: "SENSOR_ERROR",
  STALE_DATA: "STALE_DATA",
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
  OFFLINE: "OFFLINE",
} as const;

export type AgriculturalCondition = typeof AGRICULTURAL_CONDITIONS[keyof typeof AGRICULTURAL_CONDITIONS];
