"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RECOMMENDATION_PRIORITIES = exports.RECOMMENDATION_STATUSES = void 0;
exports.RECOMMENDATION_STATUSES = {
    GENERATED: "GENERATED",
    PRESENTED: "PRESENTED",
    ACKNOWLEDGED: "ACKNOWLEDGED",
    ACTION_EXPECTED: "ACTION_EXPECTED",
    REASSESSMENT_PENDING: "REASSESSMENT_PENDING",
    VERIFICATION: "VERIFICATION",
    IMPROVED: "IMPROVED",
    PARTIAL: "PARTIAL",
    NOT_IMPROVED: "NOT_IMPROVED",
    ADAPT_PLAN: "ADAPT_PLAN",
};
exports.RECOMMENDATION_PRIORITIES = {
    URGENT: "URGENT",
    HIGH: "HIGH",
    MEDIUM: "MEDIUM",
    ROUTINE: "ROUTINE",
};
