"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONFIDENCE_LEVELS = exports.FRESHNESS_STATES = exports.DATA_QUALITIES = exports.MEASUREMENT_STATES = void 0;
exports.MEASUREMENT_STATES = {
    MEASURED: "MEASURED",
    CALCULATED: "CALCULATED",
    ESTIMATED: "ESTIMATED",
    UNAVAILABLE: "UNAVAILABLE",
};
exports.DATA_QUALITIES = {
    VALID: "VALID",
    MISSING: "MISSING",
    STALE: "STALE",
    OUT_OF_RANGE: "OUT_OF_RANGE",
    SENSOR_ERROR: "SENSOR_ERROR",
    CALIBRATION_REQUIRED: "CALIBRATION_REQUIRED",
    DUPLICATE: "DUPLICATE",
    ESTIMATED: "ESTIMATED",
};
exports.FRESHNESS_STATES = {
    LIVE: "LIVE",
    RECENT: "RECENT",
    STALE: "STALE",
    OFFLINE: "OFFLINE",
    NO_DATA: "NO_DATA",
};
exports.CONFIDENCE_LEVELS = {
    HIGH: "HIGH",
    MEDIUM: "MEDIUM",
    LOW: "LOW",
    INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
};
